########################################## <dpack:main_2true>
########################################## 3:     x = 1
execute store success score pass ..ASM run data modify entity @s ArmorItems[0].tag.Stack[1] set from entity @s ArmorItems[0].tag.Consts[0]
                                                                                                                                                                                                        execute if score pass ..ASM matches 0 run tellraw @a [{"text": " !!!!!!!! FAIL: data modify entity @s ArmorItems[0].tag.Stack[1] set from entity @s ArmorItems[0].tag.Consts[0]"}]
execute store success score pass ..ASM run data modify entity @s ArmorItems[0].tag.Names.x set from entity @s ArmorItems[0].tag.Stack[1]
                                                                                                                                                                                                        execute if score pass ..ASM matches 0 run tellraw @a [{"text": " !!!!!!!! FAIL: data modify entity @s ArmorItems[0].tag.Names.x set from entity @s ArmorItems[0].tag.Stack[1]"}]
########################################## 4:     if 1 == 1:
execute store success score pass ..ASM run data modify entity @s ArmorItems[0].tag.Stack[1] set from entity @s ArmorItems[0].tag.Consts[0]
                                                                                                                                                                                                        execute if score pass ..ASM matches 0 run tellraw @a [{"text": " !!!!!!!! FAIL: data modify entity @s ArmorItems[0].tag.Stack[1] set from entity @s ArmorItems[0].tag.Consts[0]"}]
execute store success score pass ..ASM run data modify entity @s ArmorItems[0].tag.Stack[2] set from entity @s ArmorItems[0].tag.Consts[0]
                                                                                                                                                                                                        execute if score pass ..ASM matches 0 run tellraw @a [{"text": " !!!!!!!! FAIL: data modify entity @s ArmorItems[0].tag.Stack[2] set from entity @s ArmorItems[0].tag.Consts[0]"}]
execute store success score pass ..ASM run execute store result score t1 ..ASM run data get entity @s ArmorItems[0].tag.Stack[2].v
                                                                                                                                                                                                        execute if score pass ..ASM matches 0 run tellraw @a [{"text": " !!!!!!!! FAIL: execute store result score t1 ..ASM run data get entity @s ArmorItems[0].tag.Stack[2].v"}]
execute store success score pass ..ASM run execute store result score t0 ..ASM run data get entity @s ArmorItems[0].tag.Stack[1].v
                                                                                                                                                                                                        execute if score pass ..ASM matches 0 run tellraw @a [{"text": " !!!!!!!! FAIL: execute store result score t0 ..ASM run data get entity @s ArmorItems[0].tag.Stack[1].v"}]
execute store success score pass ..ASM run scoreboard players set t2 ..ASM 0
                                                                                                                                                                                                        execute if score pass ..ASM matches 0 run tellraw @a [{"text": " !!!!!!!! FAIL: scoreboard players set t2 ..ASM 0"}]
execute store success score pass ..ASM run execute if score t0 ..ASM = t1 ..ASM run scoreboard players set t2 ..ASM 1
                                                                                                                                                                                                        execute if score pass ..ASM matches 0 run tellraw @a [{"text": " !!!!!!!! FAIL: execute if score t0 ..ASM = t1 ..ASM run scoreboard players set t2 ..ASM 1"}]
execute store success score pass ..ASM run execute store result entity @s ArmorItems[0].tag.Stack[1].v int 1 run scoreboard players get t2 ..ASM
                                                                                                                                                                                                        execute if score pass ..ASM matches 0 run tellraw @a [{"text": " !!!!!!!! FAIL: execute store result entity @s ArmorItems[0].tag.Stack[1].v int 1 run scoreboard players get t2 ..ASM"}]
########################################## 4:     if 1 == 1:
execute store success score pass ..ASM run execute store result score test ..ASM run data get entity @s ArmorItems[0].tag.Stack[1].v
                                                                                                                                                                                                        execute if score pass ..ASM matches 0 run tellraw @a [{"text": " !!!!!!!! FAIL: execute store result score test ..ASM run data get entity @s ArmorItems[0].tag.Stack[1].v"}]
execute store success score pass ..ASM run execute if score test ..ASM matches 1 run function dpack:main_4true
                                                                                                                                                                                                        execute if score pass ..ASM matches 0 run tellraw @a [{"text": " !!!!!!!! FAIL: execute if score test ..ASM matches 1 run function dpack:main_4true"}]
execute store success score pass ..ASM run execute store result score test ..ASM run data get entity @s ArmorItems[0].tag.Stack[1].v
                                                                                                                                                                                                        execute if score pass ..ASM matches 0 run tellraw @a [{"text": " !!!!!!!! FAIL: execute store result score test ..ASM run data get entity @s ArmorItems[0].tag.Stack[1].v"}]
execute store success score pass ..ASM run execute if score test ..ASM matches 0 run function dpack:main_4false
                                                                                                                                                                                                        execute if score pass ..ASM matches 0 run tellraw @a [{"text": " !!!!!!!! FAIL: execute if score test ..ASM matches 0 run function dpack:main_4false"}]
########################################## </dpack:main_2true>
execute store success score pass ..ASM run execute if score ret ..ASM matches 0 run function dpack:main_4cont
                                                                                                                                                                                                        execute if score pass ..ASM matches 0 run tellraw @a [{"text": " !!!!!!!! FAIL: execute if score ret ..ASM matches 0 run function dpack:main_4cont"}]
