########################################## <dpack:main>
########################################## 1: x = 0
execute store success score pass ..ASM run data modify entity @s ArmorItems[0].tag.Stack[0] set from entity @s ArmorItems[0].tag.Consts[0]
                                                                                                                                                                                                        execute if score pass ..ASM matches 0 run tellraw @a [{"text": " !!!!!!!! FAIL: data modify entity @s ArmorItems[0].tag.Stack[0] set from entity @s ArmorItems[0].tag.Consts[0]"}]
execute store success score pass ..ASM run data modify entity @s ArmorItems[0].tag.Names.x set from entity @s ArmorItems[0].tag.Stack[0]
                                                                                                                                                                                                        execute if score pass ..ASM matches 0 run tellraw @a [{"text": " !!!!!!!! FAIL: data modify entity @s ArmorItems[0].tag.Names.x set from entity @s ArmorItems[0].tag.Stack[0]"}]
########################################## 2: if 1 >= 2:
execute store success score pass ..ASM run data modify entity @s ArmorItems[0].tag.Stack[0] set from entity @s ArmorItems[0].tag.Consts[0]
                                                                                                                                                                                                        execute if score pass ..ASM matches 0 run tellraw @a [{"text": " !!!!!!!! FAIL: data modify entity @s ArmorItems[0].tag.Stack[0] set from entity @s ArmorItems[0].tag.Consts[0]"}]
execute store success score pass ..ASM run data modify entity @s ArmorItems[0].tag.Stack[1] set from entity @s ArmorItems[0].tag.Consts[1]
                                                                                                                                                                                                        execute if score pass ..ASM matches 0 run tellraw @a [{"text": " !!!!!!!! FAIL: data modify entity @s ArmorItems[0].tag.Stack[1] set from entity @s ArmorItems[0].tag.Consts[1]"}]
execute store success score pass ..ASM run execute store result score t1 ..ASM run data get entity @s ArmorItems[0].tag.Stack[1].v
                                                                                                                                                                                                        execute if score pass ..ASM matches 0 run tellraw @a [{"text": " !!!!!!!! FAIL: execute store result score t1 ..ASM run data get entity @s ArmorItems[0].tag.Stack[1].v"}]
execute store success score pass ..ASM run execute store result score t0 ..ASM run data get entity @s ArmorItems[0].tag.Stack[0].v
                                                                                                                                                                                                        execute if score pass ..ASM matches 0 run tellraw @a [{"text": " !!!!!!!! FAIL: execute store result score t0 ..ASM run data get entity @s ArmorItems[0].tag.Stack[0].v"}]
execute store success score pass ..ASM run scoreboard players set t2 ..ASM 0
                                                                                                                                                                                                        execute if score pass ..ASM matches 0 run tellraw @a [{"text": " !!!!!!!! FAIL: scoreboard players set t2 ..ASM 0"}]
execute store success score pass ..ASM run execute if score t0 ..ASM >= t1 ..ASM run scoreboard players set t2 ..ASM 1
                                                                                                                                                                                                        execute if score pass ..ASM matches 0 run tellraw @a [{"text": " !!!!!!!! FAIL: execute if score t0 ..ASM >= t1 ..ASM run scoreboard players set t2 ..ASM 1"}]
execute store success score pass ..ASM run execute store result entity @s ArmorItems[0].tag.Stack[0].v int 1 run scoreboard players get t2 ..ASM
                                                                                                                                                                                                        execute if score pass ..ASM matches 0 run tellraw @a [{"text": " !!!!!!!! FAIL: execute store result entity @s ArmorItems[0].tag.Stack[0].v int 1 run scoreboard players get t2 ..ASM"}]
########################################## 2: if 1 >= 2:
execute store success score pass ..ASM run execute store result score test ..ASM run data get entity @s ArmorItems[0].tag.Stack[0].v
                                                                                                                                                                                                        execute if score pass ..ASM matches 0 run tellraw @a [{"text": " !!!!!!!! FAIL: execute store result score test ..ASM run data get entity @s ArmorItems[0].tag.Stack[0].v"}]
execute store success score pass ..ASM run execute if score test ..ASM matches 1 run function dpack:main_2true
                                                                                                                                                                                                        execute if score pass ..ASM matches 0 run tellraw @a [{"text": " !!!!!!!! FAIL: execute if score test ..ASM matches 1 run function dpack:main_2true"}]
execute store success score pass ..ASM run execute store result score test ..ASM run data get entity @s ArmorItems[0].tag.Stack[0].v
                                                                                                                                                                                                        execute if score pass ..ASM matches 0 run tellraw @a [{"text": " !!!!!!!! FAIL: execute store result score test ..ASM run data get entity @s ArmorItems[0].tag.Stack[0].v"}]
execute store success score pass ..ASM run execute if score test ..ASM matches 0 run function dpack:main_2false
                                                                                                                                                                                                        execute if score pass ..ASM matches 0 run tellraw @a [{"text": " !!!!!!!! FAIL: execute if score test ..ASM matches 0 run function dpack:main_2false"}]
########################################## </dpack:main>
execute store success score pass ..ASM run execute if score ret ..ASM matches 0 run function dpack:main_2cont
                                                                                                                                                                                                        execute if score pass ..ASM matches 0 run tellraw @a [{"text": " !!!!!!!! FAIL: execute if score ret ..ASM matches 0 run function dpack:main_2cont"}]
execute store success score pass ..ASM run data modify entity @s ArmorItems[0].tag.Stack[0] set from entity @s ArmorItems[0].tag.Consts[0]
                                                                                                                                                                                                        execute if score pass ..ASM matches 0 run tellraw @a [{"text": " !!!!!!!! FAIL: data modify entity @s ArmorItems[0].tag.Stack[0] set from entity @s ArmorItems[0].tag.Consts[0]"}]
execute store success score pass ..ASM run scoreboard players set ret ..ASM 1
                                                                                                                                                                                                        execute if score pass ..ASM matches 0 run tellraw @a [{"text": " !!!!!!!! FAIL: scoreboard players set ret ..ASM 1"}]
execute store success score pass ..ASM run tag @s add .ret
                                                                                                                                                                                                        execute if score pass ..ASM matches 0 run tellraw @a [{"text": " !!!!!!!! FAIL: tag @s add .ret"}]
